remote_theme: just-the-docs/just-the-docs
logo: "https://uncovered-functional-lemonade.glitch.me/assets/icon.svg"
nav_external_links:
  - title: Install bookmarklet
    url: https://uncovered-functional-lemonade.glitch.me/
footer_content: "&copy; The Glitch Chat team"
