remote_theme: just-the-docs/just-the-docs
logo: "https://uncovered-functional-lemonade.glitch.me/assets/icon.svg"
nav_external_links:
  - title: Analytics
    url: https://uncovered-functional-lemonade.glitch.me/others/analytics.html
footer_content: "&copy; The Glitch Chat team"
aux_links:
  "Install":
    - "https://uncovered-functional-lemonade.glitch.me/"

aux_links_new_tab: true
