remote_theme: just-the-docs/just-the-docs
logo: "https://uncovered-functional-lemonade.glitch.me/assets/icon.svg"
nav_external_links:
  - title: Analytics
    url: https://uncovered-functional-lemonade.glitch.me/others/analytics.html
  - title: Request a feature
    url: https://forms.reform.app/qSCZpV/feature-requests/79IGmh
footer_content: "&copy; The Glitch Chat team"
aux_links:
  "Back home":
    - "https://uncovered-functional-lemonade.glitch.me/"

aux_links_new_tab: true
